using System.Text;

// Generation — index pages and the generated blocks in <type>.md

namespace kac.core;

public static class Generator
{
    private const string Banner = "<!-- Generated by kac tooling - do not edit by hand -->";

    public static string IndexPage(TypeSchema t, List<Doc> docs)
    {
        // "Policy Index (POL)" — the type as a reader names it, then the id prefix they will meet in
        // every cross-reference. The prefix is dropped where it only repeats the name, so an ADR index
        // is headed "ADR Index" rather than "ADR Index (ADR)".
        var prefix = t.IdPrefix.ToUpperInvariant();
        var title = $"{t.DisplayName} Index"
                    + (prefix.Length > 0 && !string.Equals(prefix, t.DisplayName, StringComparison.OrdinalIgnoreCase)
                        ? $" ({prefix})"
                        : "");

        // An empty type still gets its index: every type page links to one, and link-resolves does not
        // check type root pages, so a withheld file would be an unchecked dead link. A headed table with
        // no rows says less than nothing, so an empty index says it is empty and points at the template.
        var body = docs.Count == 0
            ? $"_Nothing here yet — copy [`{Artefact.Template}`]({Artefact.Template}) to add the first._"
            : RenderTable(
                [.. t.IndexColumns.Select(Humanize)],
                [
                    .. Sorted(t, docs)
                        .Select(d => t.IndexColumns.Select(c => Cell(d, c)).ToList())
                ]);

        return $"{Banner}\n\n# {title}\n\n{body}\n";
    }

    // The two directions an index is written in. Read by SchemaChecks, so a type declaring a third word
    // is told at load rather than sorted the default way and left looking deliberate.
    public const string Descending = "descending";

    public static readonly IReadOnlySet<string> IndexOrders =
        new HashSet<string>(["ascending", Descending], StringComparer.Ordinal);

    // A record's title is its H1 rather than frontmatter, so it answers where a field is asked for and no
    // field is declared. An index column resolves it here, an export carries it, and SchemaChecks admits
    // it by this constant rather than by a string of its own.
    public const string Title = "title";

    // How a type is linked to from a generated block: the page without its extension, root-relative. The
    // form Azure DevOps renders as a wiki page and the link check resolves back to the file.
    private static string Link(TypeSchema t) =>
        "/" + (t.Page.EndsWith(".md", StringComparison.Ordinal) ? t.Page[..^3] : t.Page);

    // The decision table — what a contributor has in hand, and where it goes. The corpus's own types
    // only: a row pointing at a type this corpus never adopted is a dead link in the wiki and an
    // invitation to file a document nowhere.
    //
    // Sorted on the left column, because that is the column being read. A reader arrives holding
    // something and scans for it, so the table is ordered the way it is searched rather than by the
    // answer they do not have yet. The link carries the plural: it points at the collection.
    public static string PlacementTable(IEnumerable<TypeSchema> types) =>
        RenderTable(["You have…", "It goes in"],
        [
            .. types.OrderBy(t => t.GoesHere, StringComparer.Ordinal)
                .Select(t => new List<string> { Escape(t.GoesHere), $"[{t.PluralName}]({Link(t)})" })
        ]);

    // The types at length, under the tier that decides how each behaves. What the decision table answers
    // in a line, this answers in a paragraph — and it is grouped by tier rather than sorted flat, because
    // the reader who has got this far is learning the shape of the taxonomy rather than looking one type
    // up.
    //
    // A tier no adopted type sits in is left out entirely. A heading with nothing under it tells a reader
    // the corpus has a gap where it has in fact made a choice.
    public static string TypeCatalogue(IReadOnlyList<TierSpec> tiers, IEnumerable<TypeSchema> types)
    {
        var byTier = types.ToLookup(t => t.Tier, StringComparer.Ordinal);
        var sections = new List<string>();

        foreach (var tier in tiers)
        {
            var members = byTier[tier.Name].OrderBy(t => t.DisplayName, StringComparer.Ordinal).ToList();
            if (members.Count == 0) continue;

            var section = new StringBuilder($"### {tier.Label} — {tier.Behaviour}\n");
            if (tier.Note.Length > 0) section.Append($"\n{Wrap(tier.Note)}\n");
            foreach (var t in members)
                section.Append($"\n{Wrap($"**[{t.PluralName}]({Link(t)})** — {t.Summary} {t.Detail}")}\n");

            sections.Add(section.ToString());
        }

        return string.Join("\n", sections).TrimEnd('\n');
    }

    // One way on to each type's own field reference.
    //
    // The anchor is the heading the `schema-*` block sits under. Keeping that heading is the type page's
    // side of the bargain, and the link check holds it there.
    public static string MetadataStrip(IEnumerable<TypeSchema> types) =>
        Wrap(string.Join(" · ", types
            .OrderBy(t => t.DisplayName, StringComparer.Ordinal)
            .Select(t => $"[{t.DisplayName}]({Link(t)}#metadata)")));

    // Where each type's name came from. A type with no useful ancestor carries that as its prior art and
    // leaves the other two columns empty, which renders as an em dash. Saying a type has no ancestor is the
    // point of its row rather than a gap in it.
    public static string LineageTable(IEnumerable<TypeSchema> types) =>
        RenderTable(["Type", "Nearest prior art", "Alignment", "Divergence"],
        [
            .. types.Where(t => t.Lineage is not null)
                .OrderBy(t => t.DisplayName, StringComparer.Ordinal)
                .Select(t => new List<string>
                {
                    $"[{t.DisplayName}]({Link(t)})", Escape(t.Lineage!.PriorArt),
                    Cell(t.Lineage.Alignment), Cell(t.Lineage.Divergence)
                })
        ]);

    // An answer that is deliberately absent, written as one. An empty cell in a table of this shape reads
    // as something nobody got round to.
    private static string Cell(string text) => text.Length > 0 ? Escape(text) : "—";

    // The words a reader arrives already holding, and what they will take them to mean. Only the types
    // that collide with something appear: most do not, and a heading over a paragraph explaining that a
    // word means what it says would be worse than the silence.
    //
    // Ordered by name, because no declaration says which collision is the most dangerous — and the entry
    // that claims to be still says so wherever it lands.
    public static string Collisions(IEnumerable<TypeSchema> types) =>
        string.Join("\n\n", types
            .Where(t => t.Collision.Length > 0)
            .OrderBy(t => t.DisplayName, StringComparer.Ordinal)
            .Select(t => $"### {t.DisplayName}\n\n{Paragraphs(t.Collision)}"));

    // A folded scalar carrying more than one paragraph: YAML gives back a newline where the schema had a
    // blank line, and each paragraph is wrapped on its own.
    private static string Paragraphs(string text) =>
        string.Join("\n\n", text.Split('\n')
            .Select(p => p.Trim())
            .Where(p => p.Length > 0)
            .Select(Wrap));

    // The edges, read off the `ref:` declarations that make them checkable. One row per cross-reference
    // field a type carries, which is one row per thing an author fills in. A reciprocal pair is two rows
    // rather than one, because it is two fields, and the last column names the counterpart that ties them.
    //
    // A target the corpus has not adopted is dropped from the row, and a row left pointing nowhere goes
    // with it. The field would resolve against no document in any case; showing it would promise an edge
    // this corpus cannot have.
    public static string RelationTable(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);
        var rows = new List<List<string>>();

        foreach (var (t, name, field, targets) in Edges(types, adopted))
            rows.Add([
                t.DisplayName, $"`{name}`", string.Join(", ", targets.Select(x => x.DisplayName)),
                field.Reciprocal is { } back ? $"`{back}`" : ""
            ]);

        return RenderTable(["From", "Field", "Points at", "Answered by"], rows);
    }

    // Every cross-reference a stood-up type declares at another stood-up type, in a fixed order: by the
    // type a reader would look up, then by the field they would write.
    private static IEnumerable<(TypeSchema From, string Field, FieldSpec Spec, List<TypeSchema> To)> Edges(
        IEnumerable<TypeSchema> types, Dictionary<string, TypeSchema> adopted)
    {
        foreach (var t in types.OrderBy(t => t.DisplayName, StringComparer.Ordinal))
        foreach (var name in t.FieldOrder.OrderBy(n => n, StringComparer.Ordinal))
        {
            if (!t.Fields.TryGetValue(name, out var field) || field.Refs.Count == 0) continue;

            var targets = field.Refs.Where(adopted.ContainsKey).Select(r => adopted[r]).ToList();
            if (targets.Count > 0) yield return (t, name, field, targets);
        }
    }

    // The same edges as a diagram, which answers a different question from the table: what shape the graph
    // is, rather than which field to write. A reciprocal pair is one edge here and two rows there, and both
    // are right — the graph has one relationship where an author has two fields to fill in.
    //
    // Written to the subset of Mermaid an Azure DevOps wiki renders, which is narrower than Mermaid's own
    // and fails silently where it is exceeded: `graph`, never `flowchart`; `-->`, never a longer arrow; and
    // no subgraphs, because ADO does not support links crossing one. GitHub renders this subset too, so the
    // fenced form is used rather than ADO's `:::` container, which GitHub shows as literal text.
    //
    // Edges are labelled `-- text -->` rather than `-->|text|`. The two are the same diagram, but a
    // markdown formatter reading a file for tables finds pipes in the second and reformats what it takes
    // for cells — `superseded-by` came back as `superseded - by`, inside a fenced block it should never
    // have entered. `generate --check` catches it, which is the guard working; not provoking it is better.
    public static string RelationDiagram(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);
        var diagram = new StringBuilder("```mermaid\ngraph LR;\n");

        foreach (var t in adopted.Values.OrderBy(t => t.DisplayName, StringComparer.Ordinal))
            diagram.Append($"  {Node(t.Key)}[{t.DisplayName}];\n");

        // Reciprocal halves collapse into the one edge they describe; whichever half is met first names it.
        var drawn = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (from, name, field, targets) in Edges(types, adopted))
        foreach (var to in targets)
        {
            var pair = string.CompareOrdinal(from.Key, to.Key) < 0
                ? $"{from.Key}|{to.Key}"
                : $"{to.Key}|{from.Key}";
            if (field.Reciprocal is not null && !drawn.Add(pair)) continue;

            diagram.Append($"  {Node(from.Key)} -- {name} --> {Node(to.Key)};\n");
        }

        return diagram.Append("```").ToString();
    }

    // A mermaid node id. Prefixed and reduced to word characters so that a type whose folder carries a
    // hyphen, or is spelled `end`, cannot collide with the diagram's own grammar.
    private static string Node(string key) =>
        "t_" + new string([.. key.Select(c => char.IsLetterOrDigit(c) ? c : '_')]);

    // The calls that are genuinely close. A pair needs both of its types to say anything at all, so one
    // adopted and one not leaves the pair out — a corpus with no controls is not helped by being told how
    // a standard differs from one.
    //
    // Sorted by heading, because that is the line a reader scans. The pair a type declares is rendered from
    // that type's side, so the heading names the declaring type first and the reader meets the two in the
    // order the sentence beneath them uses.
    public static string Disambiguations(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);

        var entries = new List<(string Heading, string Text)>();
        foreach (var t in types)
        foreach (var (other, text) in t.Versus)
            if (adopted.TryGetValue(other, out var against))
                entries.Add(($"{t.DisplayName} vs {against.DisplayName}", text));

        return string.Join("\n\n", entries
            .OrderBy(e => e.Heading, StringComparer.Ordinal)
            .Select(e => Wrap($"**{e.Heading}.** {e.Text}")));
    }

    // Prose at the corpus's own margin. Generated tables are exempt from it because a cell cannot be
    // broken; a paragraph can, and one long line in a file everything else wraps reads as the generator
    // exempting itself from the rule it is regenerating the file to enforce.
    private const int Margin = 120;

    private static string Wrap(string text)
    {
        var line = new StringBuilder();
        var wrapped = new StringBuilder();

        foreach (var word in Unbreakable(text))
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > Margin)
            {
                wrapped.Append(line).Append('\n');
                line.Clear();
            }

            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }

        return wrapped.Append(line).ToString();
    }

    // The units a line may be broken between. Words, except that a markdown link is one unit however many
    // spaces its label holds: `[RFC 2119](…)` broken after `RFC` still renders, but it reads badly in the
    // source and a formatter meeting it will put it back — and the generator would then write it out
    // again on the next run. A word longer than the margin is left whole, a URL being the usual case.
    private static IEnumerable<string> Unbreakable(string text)
    {
        var words = text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        var link = new StringBuilder();

        foreach (var word in words)
        {
            if (link.Length == 0 && !word.StartsWith('[') && !word.StartsWith("**[", StringComparison.Ordinal))
            {
                yield return word;
                continue;
            }

            if (link.Length > 0) link.Append(' ');
            link.Append(word);

            // Closed once the target that follows the label has closed too. A bracket in prose that never
            // reaches one is released at the end, rather than swallowing the rest of the paragraph.
            if (word.Contains(')', StringComparison.Ordinal))
            {
                yield return link.ToString();
                link.Clear();
            }
        }

        if (link.Length > 0) yield return link.ToString();
    }

    // The corpus's own index of types, for whoever arrives at the corpus root: what each holds, and
    // one way on to the taxonomy, which is where the question "so where does mine go" is answered. The
    // pointer sits inside the block so that it cannot drift above the table or be edited away.
    //
    // Sorted by name, because a reader looking a type up already knows its name. Tier is a column rather
    // than a grouping for the same reason: worth seeing beside a type, and not how anyone arrives.
    public static string TypesIndex(IEnumerable<TypeSchema> types, string taxonomyPath) =>
        RenderTable(["Type", "Tier", "What it holds"],
        [
            .. types.OrderBy(t => t.DisplayName, StringComparer.Ordinal).Select(t => new List<string>
                { $"[{t.DisplayName}]({Link(t)})", t.Tier, Escape(t.Summary) })
        ])
        + "\n\n" + Wrap($"**Where does a document go?** The [taxonomy]({taxonomyPath}) has the decision table, "
                        + "what each type is and is not, and the calls that are genuinely close.");

    // The rows of an index, in the order the type's `index` block asks for. Sorting on several columns
    // is a sort by the first, ties broken by the next; the direction applies to the whole ordering,
    // because a type that wanted one column each way would be asking for two questions in one key.
    //
    // A type declaring no `sort:` is sorted by id, which is the one column every document carries.
    private static IEnumerable<Doc> Sorted(TypeSchema t, List<Doc> docs)
    {
        var keys = t.IndexSort.Count > 0 ? t.IndexSort : ["id"];
        var descending = t.IndexOrder == Descending;

        var ordered = descending
            ? docs.OrderByDescending(d => d.FrontScalar(keys[0]) ?? "", StringComparer.Ordinal)
            : docs.OrderBy(d => d.FrontScalar(keys[0]) ?? "", StringComparer.Ordinal);

        return keys.Skip(1).Aggregate(ordered, (acc, key) => descending
            ? acc.ThenByDescending(d => d.FrontScalar(key) ?? "", StringComparer.Ordinal)
            : acc.ThenBy(d => d.FrontScalar(key) ?? "", StringComparer.Ordinal));
    }

    private static string Cell(Doc d, string col)
    {
        if (col == Title)
        {
            var file = Path.GetFileName(d.Rel);
            return $"[{Escape(d.H1 ?? "")}]({file})";
        }

        return Escape(d.FrontScalar(col) ?? "");
    }

    // The frontmatter reference on a type page: every field a document of that type carries, universal
    // ones included, so the page an author writes from is complete without sending them to metadata.md
    // for id, tier and owner.
    //
    // Universal fields come first, in the universal order, and are read through EffectiveField so a type
    // that refines one (every type narrows `status` to its own values) shows the refinement rather than
    // the universal placeholder. They are marked rather than separated: one table is one scan, which is
    // what someone filling in frontmatter wants.
    public static string SchemaTable(TypeSchema t, Schema s)
    {
        List<string> headers = ["Field", "Value", "Notes"];
        var universal = s.UniversalOrder.Where(n => s.EffectiveField(t, n) is not null).ToList();
        var own = t.FieldOrder.Where(n => !universal.Contains(n)).ToList();

        var rows = universal.Select(n => FieldRow(n, s.EffectiveField(t, n)!, true))
            .Concat(own.Select(n => FieldRow(n, t.Fields[n], false)))
            .ToList();

        var order = universal.Concat(own).ToList();
        var specs = order.Select(n => s.EffectiveField(t, n)!).ToList();
        var table = RenderTable(headers, rows);
        return table + Legend(specs.Any(f => f.Required), universal.Count > 0);

        // `tier` is the one field whose value a type settles rather than chooses from: every document in
        // the folder carries the same one, and CI fails any that does not. Offering the reader the other
        // four would be offering four ways to fail a check.
        List<string> FieldRow(string name, FieldSpec f, bool universal) =>
        [
            $"`{name}`{Marks(f.Required, universal)}",
            name == "tier" && t.Tier.Length > 0 ? $"`{t.Tier}`" : ValueFor(f),
            NotesFor(f)
        ];
    }

    // What a field may hold: its type, or — where the type is an enum with a resolved set — the values
    // themselves. The word `enum` tells an author nothing they can write into frontmatter, and the set
    // is what they came to the page for, so the set is what the column carries.
    private static string ValueFor(FieldSpec f) =>
        f is { Type: "enum", Values.Count: > 0 }
            ? string.Join(" ", f.Values!.Select(v => $"`{v}`"))
            : f.Type;

    // The same reference for metadata.md, which documents the universal fields once for the whole
    // taxonomy. Values are the unrefined universal declarations — `status` is genuinely "varies by
    // type" here, because there is no type in hand to narrow it.
    public static string UniversalSchemaTable(Schema s)
    {
        List<string> headers = ["Field", "Value", "Notes"];
        var fields = s.UniversalOrder.Where(s.Universal.ContainsKey).Select(n => s.Universal[n]).ToList();
        var rows = fields
            .Select(f => new List<string>
                { $"`{f.Name}`{Marks(f.Required, false)}", ValueFor(f), NotesFor(f) })
            .ToList();
        return RenderTable(headers, rows) + Legend(fields.Any(f => f.Required), false);
    }

    // Required and universal are marked on the field name rather than given a column of their own: a
    // column that is empty in most rows costs a full column's width to say one bit. The markers read in
    // the order the legend below the table explains them.
    private static string Marks(bool required, bool universal)
    {
        var marks = (required ? "*" : "") + (universal ? "†" : "");
        return marks.Length == 0 ? "" : $" {marks}";
    }

    // One paragraph beneath the table, a line to each marker. The two are joined by a hard break —
    // two trailing spaces — rather than a blank line, because they are one legend rather than two
    // paragraphs, and rather than spaces on one line, because HTML collapses a run of those to a
    // single gap. The asterisk is escaped: a line opening with a bare one is a bullet.
    private static string Legend(bool anyRequired, bool anyUniversal)
    {
        List<string> parts = [];
        if (anyRequired) parts.Add("\\* Field is required");
        if (anyUniversal)
            parts.Add("† Carried by every document in the taxonomy — see "
                      + "[Metadata](/knowledge-as-code/metadata.md).");
        return parts.Count == 0 ? "" : "\n\n" + string.Join("  \n", parts);
    }

    // Enum values are not repeated here — they are the Value column, see ValueFor. A required-when
    // condition closes the cell as its own sentence, quoted exactly as the schema writes it, because
    // it is the difference between a field an author may skip and one they may not.
    private static string NotesFor(FieldSpec f)
    {
        var notes = Escape(f.TableText ?? "");
        if (string.IsNullOrEmpty(f.RequiredWhen)) return notes;

        var when = $"Required when `{Escape(f.RequiredWhen)}`.";
        return notes.Length == 0 ? when : $"{notes} {when}";
    }

    // What a description may run to. The checks table is read by scanning — a reader wants to know which
    // row is the one they tripped, not to read a paragraph about every check on the page — and a cell that runs
    // to several sentences is one that has taken on the message's job as well as its own. A description
    // says what is verified; a rule's `message:` says what to do about it, and is where the author who
    // tripped it will read the reasoning. Held here because the table is what makes this a limit, and read
    // by SchemaChecks so a schema's own rules are held to the same bound as the rows written below.
    public const int DescriptionMax = 120;

    // The reader-facing "What CI checks" table: a curated, grouped view of the catalogue that `kac generate`
    // splices into every type page. It is deliberately not the raw catalogue — related checks are folded
    // into one row (the three `id-*` checks read as one `id` row) and worded for a human skim. Generating
    // it from the catalogue instead would change what the table means, so each row names the catalogue
    // ids it stands for and ChecksTableProblems verifies the coverage, leaving the wording hand-tuned.
    //
    // `When` is the row's applicability: null fires for every type, otherwise the predicate asks the
    // type's own schema whether the check can fire at all — so a policy page does not advertise that its
    // documents are checked for Y-statements. Read from the schema rather than hand-listed per type, so
    // declaring a rule remains the only thing needed to document it.
    private static readonly (string Label, CheckId[] Ids, string Description, Func<TypeSchema, bool>? When)[] DocRows =
    [
        ("frontmatter-parses", [new("frontmatter-parses")], "Frontmatter is present and is a valid YAML mapping.",
            null),
        ("unknown-key", [new("unknown-key")], "Every frontmatter key is a schema field or a reserved ADO key.", null),
        ("key-order", [new("key-order")], "Key order is a topological extension of the schema's field order.", null),
        ("required-field", [new("required-field")], "Required and conditionally-required fields are present.", null),
        ("bare-key", [new("bare-key")], "An absent value is a bare key, never `null`, `~`, `\"\"` or `—`.", null),
        ("date-quoted / date-format", [new("date-quoted"), new("date-format")],
            "Date fields are quoted, and name a day the calendar has — `YYYY-MM-DD`.", null),
        ("enum", [new("enum"), new("enum-lowercase")], "Enum values are in range and lowercase.", null),
        ("field-pattern", [new("field-pattern")],
            "Values match the pattern their field declares (e.g. `tags`).", null),
        ("min-items", [new("min-items")],
            "A list field carries at least as many entries as its schema asks for.",
            t => t.AnyField(f => f.MinItems is not null)),
        ("list-order", [new("list-order")],
            "List entries read in alphabetical order, with numbers compared as numbers.", null),
        ("min-records", [new("min-records")],
            "A value in a grouping field is carried by at least as many records as the schema asks for.",
            t => t.AnyField(f => f.MinRecords is not null)),
        ("tier-matches-type", [new("tier-matches-type")], "`tier` matches the tier the type declares.", null),
        // Which of the three shapes an id takes is the type's to decide, so the row says that a shape is
        // held to rather than listing the styles a reader could be on any of.
        ("id", [new("id-prefix"), new("id-format"), new("id-matches-filename")],
            "`id` carries the type's prefix, takes the shape the type declares, and names the same document "
            + "as the filename.", null),
        ("id-unique", [new("id-unique")], "`id` is unique across the whole corpus.", null),
        ("filename / slug-length", [new("filename-pattern"), new("slug-length")],
            "Filename matches the pattern; the slug is within 30 characters.", null),
        ("h1", [new("h1")], "The document has an H1.", null),
        ("identity", [new("identity"), new("identity-type"), new("identity-id"), new("identity-status")],
            "An identity line beneath the H1 names the type, id and status, and all three agree with the frontmatter.",
            null),
        ("sections", [new("required-section"), new("empty-section")],
            "Every required section heading is present, and no declared section is left as a bare heading.", null),
        ("placeholder-left", [new("placeholder-left")],
            "No `{{…}}` from the template is left unfilled, outside code.", null),
        // The pipe is escaped because this text lands in a table cell: GFM splits a cell on a bare `|`
        // even inside a code span, so an unescaped one would break the row it is describing.
        ("clauses", [new("clause-table"), new("clause-id-format"), new("clause-modal")],
            "The clause section is a table of `Id \\| Clause` rows, each id a code span and each "
            + "clause opening with its modal.", t => t.Parts?.Source == PartSpec.Table),
        ("clause-order / clause-compound", [new("clause-order"), new("clause-compound")],
            "Clause rows are grouped by binding level, and each carries a single obligation.",
            t => t.Parts?.Source == PartSpec.Table),
        // What the `clauses` rows ask of a table, asked of the source that writes its parts as headings.
        ("part-none / part-empty", [new("part-none"), new("part-empty")],
            "The parts section holds at least one heading, and each has something under it.",
            t => t.Parts?.Source == PartSpec.Headings),
        // Shown on the pages of the types that keep addressable parts, rather than on every page. Both
        // checks run corpus-wide, since a citation is checked where it is written and any document may
        // carry one; what this predicate scopes is the documentation, and a type whose records have no
        // parts has no reason to describe how one is cited.
        ("part-id-unique / part-ref", [new("part-id-unique"), new("part-ref")],
            "No two parts of a record share an address, and a `record-id.part` citation reaches the part "
            + "it names.", t => t.Parts is not null),
        ("link-resolves", [new("link-resolves"), new("fragment-resolves")],
            "Every internal link resolves (all forms, `.md` optional), and a `#fragment` names a heading there.",
            null),
        ("undefined-label", [new("undefined-label")], "Every shortcut reference has a link definition.", null),
        ("label-canonical", [new("label-canonical")],
            "A shortcut label that names a document is written as that document's id.", null),
        ("related-matches-section", [new("related-matches-section")],
            "A field that mirrors a section reconciles with the ids in that section.",
            t => t.AnyField(f => f.MirrorsSection is not null)),
        ("ref-resolves", [new("ref-resolves")],
            "An id in a field that references another document names one that exists, of the type the field names.",
            t => t.AnyField(f => f.Refs.Count > 0)),
        ("reciprocal", [new("reciprocal")], "A reciprocal field and its counterpart agree in both directions.",
            t => t.AnyField(f => f.Reciprocal is not null)),
        ("unused-definition", [new("unused-definition")], "A link definition that nothing references.", null),
        ("y-statement", [new("y-statement")],
            "A Y-statement block-quote follows the H1, states all six moves, and is within its word ceiling.",
            null),
        ("alternatives-verdict", [new("alternatives-verdict")], "Each Alternatives Considered bullet states a verdict.",
            null),
        ("terms-alphabetical", [new("terms-alphabetical")], "A glossary's entries read in alphabetical order.", null),
        ("dependency-cycle", [new("dependency-cycle")],
            "A cycle in the dependency graph these records form, naming every record the loop runs through.", null)
    ];

    // Which rule class reports under which check id, read from the registries rather than written out.
    // A row whose checks come from a rule class belongs on a type page only where that type declares
    // the rule — and naming the rule id here instead would let a rename stop a page advertising the
    // check, silently and correctly-looking.
    private static readonly IReadOnlyDictionary<CheckId, RuleId> RuleByCheck =
        DocumentRules.All.SelectMany(r => r.Emits.Select(c => (Check: c, r.RuleId)))
            .Concat(CorpusRules.All.SelectMany(r => r.Emits.Select(c => (Check: c, r.RuleId))))
            .ToDictionary(x => x.Check, x => x.RuleId);

    // A row applies where its own predicate allows it and where the type declares whatever rule class
    // reports its checks. A row naming no rule-class check is unconstrained by the second half.
    private static bool Applies((string Label, CheckId[] Ids, string Description, Func<TypeSchema, bool>? When) row,
        TypeSchema t) =>
        (row.When is null || row.When(t))
        && row.Ids.All(id => !RuleByCheck.TryGetValue(id, out var rule) || t.HasRule(rule));

    // The curated rows, then a row for each expression rule the type declares. A core check is worded
    // here because several ids fold into one reader-facing row; an expression rule is one id reporting
    // under its own name, and its `description:` in the schema is already that row written out. Copying
    // it here would be the same sentence in two files, drifting apart at the first edit.
    //
    // Beneath both, the rules the type declares and nothing runs. See Intentions.
    public static string ChecksTable(Schema schema, TypeSchema t)
    {
        var severity = schema.Checks.ToDictionary(c => c.Id, c => c.Severity);
        List<string> headers = ["Check", "Level", "What it verifies"];
        var rows = DocRows.Where(r => Applies(r, t)).Select(r => new List<string>
        {
            $"`{r.Label}`",
            severity.GetValueOrDefault(r.Ids[0], Sev.Error).ToString().ToLowerInvariant(),
            r.Description
        }).ToList();

        rows.AddRange(t.Rules.Where(r => r.Compiled is not null).Select(r => new List<string>
        {
            $"`{r.Id}`",
            (r.Severity ?? Sev.Warning).ToString().ToLowerInvariant(),
            Escape(r.Description ?? r.Message ?? "")
        }));

        return RenderTable(headers, rows) + Intentions(t);
    }

    // The rules the type declares that nothing runs — no `expr:`, no implementation. Each is a real
    // decision about what this type should be held to, and each is unenforced, so a page that showed
    // only the table above would say the schema promises nothing more than CI delivers. It promises
    // rather a lot more, and that is worth a reader knowing before they rely on it.
    //
    // Kept apart from the table rather than folded in as rows, because the two answer different
    // questions: one is what a build will say about a document, the other what has been written down
    // and not built. A rule leaves this block by gaining an `expr:` or a class, at which point it
    // appears above under its own name.
    private static string Intentions(TypeSchema t)
    {
        var intended = t.Rules
            .Where(r => r.Compiled is null
                        && !DocumentRules.ByRuleId.ContainsKey(r.Id)
                        && !CorpusRules.ByRuleId.ContainsKey(r.Id))
            .ToList();
        if (intended.Count == 0) return "";

        List<string> headers = ["Rule", "What it would verify"];
        var rows = intended
            .Select(r => new List<string> { $"`{r.Id}`", Escape(r.Description ?? r.Message ?? "") })
            .ToList();
        return "\n\n**Declared, not yet enforced** — carried by the schema, run by nothing.\n\n"
               + RenderTable(headers, rows);
    }

    // Reconcile the curated table with the catalogue. Empty means the reader-facing table is a
    // faithful, complete view of what the validator enforces; any entry is a drift a human must
    // resolve. `kac checks` calls this and fails on a non-empty result, which the test suite asserts.
    public static IReadOnlyList<string> ChecksTableProblems(Schema schema)
    {
        var catalogue = schema.Checks.Select(c => c.Id).ToHashSet();
        var advertised = schema.Checks.Where(c => c.OnTypePage).Select(c => c.Id).ToHashSet();
        var documented = DocRows.SelectMany(r => r.Ids).ToHashSet();

        var problems = new List<string>();

        foreach (var id in documented.Where(id => !catalogue.Contains(id)).Order())
            problems.Add($"the checks table documents '{id}', which the schema does not declare (stale row).");
        foreach (var id in advertised.Where(id => !documented.Contains(id)).Order())
            problems.Add($"check '{id}' has no row in the checks table. Write one, or declare "
                         + "'on-type-page: false' where the schema declares the check.");
        foreach (var id in documented.Where(id => catalogue.Contains(id) && !advertised.Contains(id)).Order())
            problems.Add($"check '{id}' declares 'on-type-page: false' and has a row anyway — drop one of the two.");

        // The rows written above, held to the bound a schema's rules are held to. Nothing else would
        // notice: these are C# literals rendered into a generated table, so a row that grows past it
        // reads as intentional in the diff and as noise on the page.
        foreach (var row in DocRows.Where(r => r.Description.Length > DescriptionMax))
            problems.Add($"the checks table row '{row.Label}' has a {row.Description.Length}-character "
                         + $"description; the limit is {DescriptionMax}.");

        return problems;
    }

    private const string BeginMarker = "<!-- BEGIN GENERATED: ";
    private const string EndMarker = "<!-- END GENERATED: ";
    private const string MarkerClose = " -->";

    public static string SpliceBlock(string text, string name, string inner)
    {
        var begin = $"{BeginMarker}{name}{MarkerClose}";
        var end = $"{EndMarker}{name}{MarkerClose}";
        var bi = text.IndexOf(begin, StringComparison.Ordinal);
        if (bi < 0) return text;
        var ei = text.IndexOf(end, bi, StringComparison.Ordinal);
        if (ei < 0) return text;

        // A block with nothing to say closes on the next line. Padding it out to the usual blank line
        // either side leaves two of them and reads as content someone deleted. Several blocks are
        // legitimately empty in a corpus that adopted few types: no pair of its types is easily confused,
        // and none of the words it kept collides with anything.
        var body = inner.Length == 0 ? "\n" : $"\n\n{inner}\n\n";
        return text[..(bi + begin.Length)] + body + text[ei..];
    }

    // A page with its generated blocks emptied, leaving the markers and everything a person wrote.
    //
    // `mechanism --check` compares this, so a shared page may carry a block derived from the corpus holding
    // it. Two corpora running the same framework hold the same prose and a different table beneath it, and
    // both are correct. The division is exact: `generate --check` answers for the generated half against
    // the local schema, `mechanism --check` for the authored half against the reference, and neither has an
    // opinion about the other's.
    //
    // The markers stay, so deleting a block — rather than regenerating it — is still drift. An unclosed
    // marker leaves the rest of the page compared as written, which is the honest reading of a file whose
    // structure the generator can no longer follow.
    public static string Authored(string text)
    {
        var sb = new StringBuilder();
        var at = 0;

        while (true)
        {
            var bi = text.IndexOf(BeginMarker, at, StringComparison.Ordinal);
            if (bi < 0) break;
            var opened = text.IndexOf(MarkerClose, bi, StringComparison.Ordinal);
            if (opened < 0) break;
            opened += MarkerClose.Length;
            var ei = text.IndexOf(EndMarker, opened, StringComparison.Ordinal);
            if (ei < 0) break;

            sb.Append(text, at, opened - at);
            at = ei;
        }

        return sb.Append(text, at, text.Length - at).ToString();
    }

    // Deterministic GFM table: fixed column widths, single-space padding, LF joins,
    // no trailing newline (callers add their own).
    private static string RenderTable(List<string> headers, List<List<string>> rows)
    {
        var n = headers.Count;
        var w = new int[n];
        for (var i = 0; i < n; i++) w[i] = headers[i].Length;
        foreach (var row in rows)
            for (var i = 0; i < n; i++)
                w[i] = Math.Max(w[i], row[i].Length);

        List<string> lines =
        [
            Row(headers, w), Sep(w),
            .. rows.Select(r => Row(r, w))
        ];
        return string.Join("\n", lines);
    }

    private static string Row(List<string> cells, int[] w)
    {
        var sb = new StringBuilder("|");
        for (var i = 0; i < cells.Count; i++)
            sb.Append(' ').Append(cells[i].PadRight(w[i])).Append(" |");
        return sb.ToString();
    }

    // Dashes fill the cell, padding spaces included: |------| rather than | ---- |. Both are valid
    // GFM and the row width is identical, but this is the form markdown formatters normalise to, and
    // a generated file that an editor reformats on save is a permanently dirty working tree.
    private static string Sep(int[] w)
    {
        var sb = new StringBuilder("|");
        foreach (var width in w)
            sb.Append(new string('-', Math.Max(3, width + 2))).Append('|');
        return sb.ToString();
    }

    private static string Humanize(string col)
    {
        if (col == "id") return "ID";
        var s = col.Replace('-', ' ');
        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    private static string Escape(string cell)
        => cell.Replace("\r", " ").Replace("\n", " ").Replace("|", "\\|");
}
