using System.Text;

namespace kac.core;

// What `generate` writes into a corpus: an index page per type, and the body of every generated block a
// framework page carries.
//
// `GeneratedFiles` is the one list of which renderer fills which block, and is the only caller of most of
// what is below. The marker protocol those blocks live between is `Markers`, the table form they are
// written in is `Gfm`, and the checks table one of them carries is `ChecksTable`.
public static class Generator
{
    private const string Banner = "<!-- Generated by kac tooling - do not edit by hand -->";

    public static string IndexPage(TypeSchema t, List<Doc> docs)
    {
        // "Policy Index (POL)": the type as a reader names it, then the id prefix they meet in every
        // cross-reference. Where the prefix only repeats the name it is dropped, so an ADR index is headed
        // "ADR Index" rather than "ADR Index (ADR)".
        var prefix = t.IdPrefix.ToUpperInvariant();
        var title = $"{t.DisplayName} Index"
                    + (prefix.Length > 0 && !string.Equals(prefix, t.DisplayName, StringComparison.OrdinalIgnoreCase)
                        ? $" ({prefix})"
                        : "");

        // An empty type still gets its index, because every type page links to one and a withheld file
        // fails link-resolves. A headed table with no rows says less than nothing, so an empty index says
        // it is empty and points at the template.
        if (docs.Count == 0)
            return $"{Banner}\n\n# {title}\n\n"
                   + $"_Nothing here yet. Copy [`{Artefact.Template}`]({Artefact.Template}) to add the first._\n";

        // Rows are sorted before they are grouped, so the type's declared `sort:` orders each table and
        // the grouping only decides which table a row lands in.
        var located = t.Fields.Values.FirstOrDefault(f => f.From == Doc.SubPath)?.Name;
        var groups = Sorted(t, docs)
            .GroupBy(d => Group(d, located))
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => (g.Key, Rows: g.ToList()))
            .ToList();

        var body = string.Join("\n\n", groups.Select(g => g.Key.Length == 0
            ? Table(t, located, g.Key, g.Rows)
            : $"## {GroupHeading(g.Key)}\n\n{Table(t, located, g.Key, g.Rows)}"));

        return $"{Banner}\n\n# {title}\n\n{body}\n";
    }

    // Which table a row lands in: the first folder under the type, and nothing below it. A type nesting
    // two deep would otherwise scatter four records across three headings, and a reader scanning for a
    // standard about Node has to already know that Node sits under Platform.
    //
    // A type deriving nothing from where its records sit has one group, keyed on the empty string, which
    // is the index as it reads without folders.
    private static string Group(Doc d, string? located)
    {
        if (located is null) return "";
        var sub = d.FrontScalar(located) ?? "";
        var cut = sub.IndexOf('/');
        return cut < 0 ? sub : sub[..cut];
    }

    // One group's table. The derived column is dropped where every row repeats the heading above it,
    // and where a corpus using no folders leaves it empty in every row. A record filed deeper keeps it,
    // because `platform/node` under a heading of Platform is the one place `node` is written down.
    // `docs/design/generation.md` states the rule for whoever reads the index.
    private static string Table(TypeSchema t, string? located, string key, List<Doc> rows)
    {
        var columns = located is not null && rows.All(d => (d.FrontScalar(located) ?? "") == key)
            ? t.IndexColumns.Where(c => c != located).ToList()
            : t.IndexColumns.ToList();

        return Gfm.RenderTable(
            [.. columns.Select(Humanize)],
            [.. rows.Select(d => columns.Select(c => Cell(d, c, t)).ToList())]);
    }

    // A folder names its group, title-cased for the heading. `Humanize` is not reused: it turns `id`
    // into `ID`, which is true of the field and not of a folder carrying the same three letters.
    private static string GroupHeading(string key) =>
        char.ToUpperInvariant(key[0]) + key[1..].Replace('-', ' ');

    // The two directions an index is written in. SchemaChecks reads this set, so a type declaring a third
    // word is told at load rather than sorted the default way and left looking deliberate.
    public const string Descending = "descending";

    public static readonly IReadOnlySet<string> IndexOrders =
        new HashSet<string>(["ascending", Descending], StringComparer.Ordinal);

    // A record's title is its H1 and not a frontmatter field, so this constant answers wherever a field
    // named `title` is asked for. An index column resolves it here, Exporter carries it, and SchemaChecks
    // admits it by this constant rather than by a string of its own.
    public const string Title = "title";

    // How a generated block links to a type: the page itself, reached from the block's own file. `up`
    // climbs to the corpus root, so the link resolves wherever the corpus sits, whether that is a wiki
    // root or a subfolder of a documentation site. Naming the file rather than the folder is what stops
    // the link depending on a renderer that maps one to the other.
    // Types paired with the lineage they declare, dropping those declaring none. A `Where` cannot tell
    // the `Select` below it that it settled the value, so the pair is made here and carries it.
    private static IEnumerable<(TypeSchema Type, LineageSpec Lineage)> WithLineage(
        IEnumerable<TypeSchema> types)
    {
        foreach (var t in types)
            if (t.Lineage is { } lineage) yield return (t, lineage);
    }

    private static string Link(TypeSchema t, string up) => up + t.Page;

    // The decision table: what a contributor has in hand, and where it goes. The corpus's own types
    // only, because a row pointing at a type this corpus never adopted is a dead link in the wiki and an
    // invitation to file a document nowhere.
    //
    // Sorted on the left column, because a reader arrives holding something and scans for it. Ordering by
    // the right column would sort the table by the answer they came for and do not have yet. The link
    // carries the plural: it points at the collection.
    public static string PlacementTable(IEnumerable<TypeSchema> types, string up) =>
        Gfm.RenderTable(["You have…", "It goes in"],
        [
            .. types.OrderBy(t => t.GoesHere, StringComparer.Ordinal)
                .Select(t => new List<string> { Gfm.Escape(t.GoesHere), $"[{t.PluralName}]({Link(t, up)})" })
        ]);

    // The types at length, under the tier that decides how each behaves. What the decision table answers
    // in a line, this answers in a paragraph. Grouped by tier rather than sorted flat: a reader who has
    // got this far is learning the shape of the taxonomy, not looking one type up.
    //
    // A tier no adopted type sits in is left out entirely. A heading with nothing under it tells a reader
    // the corpus has a gap where it has in fact made a choice.
    public static string TypeCatalogue(IReadOnlyList<TierSpec> tiers, IEnumerable<TypeSchema> types, string up)
    {
        var byTier = types.ToLookup(t => t.Tier, StringComparer.Ordinal);
        var sections = new List<string>();

        foreach (var tier in tiers)
        {
            var members = byTier[tier.Name].OrderBy(t => t.DisplayName, StringComparer.Ordinal).ToList();
            if (members.Count == 0) continue;

            var section = new StringBuilder($"### {tier.Label}: {tier.Behaviour}\n");
            if (tier.Note.Length > 0) section.Append($"\n{Wrap(tier.Note)}\n");
            foreach (var t in members)
                section.Append($"\n{Wrap($"**[{t.PluralName}]({Link(t, up)}).** {t.Summary} {t.Detail}")}\n");

            sections.Add(section.ToString());
        }

        return string.Join("\n", sections).TrimEnd('\n');
    }

    // One way on to each type's own field reference. The anchor is the heading the `schema-*` block sits
    // under: keeping that heading is the type page's side of the bargain, and fragment-resolves holds it
    // there.
    public static string MetadataStrip(IEnumerable<TypeSchema> types, string up) =>
        Wrap(string.Join(" · ", types
            .OrderBy(t => t.DisplayName, StringComparer.Ordinal)
            .Select(t => $"[{t.DisplayName}]({Link(t, up)}#metadata)")));

    // Where each type's name came from. A type with no useful ancestor carries that as its prior art and
    // leaves the other two columns empty, and an empty cell renders as an em dash. Saying a type has no
    // ancestor is the point of its row rather than a gap in it.
    public static string LineageTable(IEnumerable<TypeSchema> types, string up) =>
        Gfm.RenderTable(["Type", "Nearest prior art", "Alignment", "Divergence"],
        [
            .. WithLineage(types)
                .OrderBy(x => x.Type.DisplayName, StringComparer.Ordinal)
                .Select(x => new List<string>
                {
                    $"[{x.Type.DisplayName}]({Link(x.Type, up)})", Gfm.Escape(x.Lineage.PriorArt),
                    Cell(x.Lineage.Alignment), Cell(x.Lineage.Divergence)
                })
        ]);

    // An answer that is deliberately absent, written as one. An empty cell in a table of this shape reads
    // as something nobody got round to.
    private static string Cell(string text) => text.Length > 0 ? Gfm.Escape(text) : "—";

    // The words a reader arrives already holding, and what they take those words to mean. Only the types
    // that collide with something appear. Most do not, and a heading over a paragraph explaining that a
    // word means what it says would be worse than the silence.
    //
    // Ordered by name, because no declaration says which collision is the most dangerous. The entry that
    // claims to be still says so wherever it lands.
    public static string Collisions(IEnumerable<TypeSchema> types) =>
        string.Join("\n\n", types
            .Where(t => t.Collision.Length > 0)
            .OrderBy(t => t.DisplayName, StringComparer.Ordinal)
            .Select(t => $"### {t.DisplayName}\n\n{Paragraphs(t.Collision)}"));

    // A folded scalar carrying more than one paragraph: YAML gives back a newline where the schema holds
    // a blank line, and Wrap then runs over each paragraph on its own.
    private static string Paragraphs(string text) =>
        string.Join("\n\n", text.Split('\n')
            .Select(p => p.Trim())
            .Where(p => p.Length > 0)
            .Select(Wrap));

    // The edges, read off the `ref:` declarations that make them checkable. One row per cross-reference
    // field a type carries, which is one row per thing an author fills in. A reciprocal pair is two rows
    // rather than one, because it is two fields. The last column names the counterpart that ties them.
    //
    // A target the corpus has not adopted is dropped from the row, and a row left pointing nowhere goes
    // with it. The field would resolve against no document in any case. Showing it would promise an edge
    // this corpus cannot have.
    public static string RelationTable(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);
        var rows = new List<List<string>>();

        foreach (var (t, name, field, targets) in Edges(types, adopted))
            rows.Add([
                t.DisplayName, $"`{name}`", string.Join(", ", targets.Select(x => x.DisplayName)),
                field.Reciprocal is { } back ? $"`{back}`" : ""
            ]);

        return Gfm.RenderTable(["From", "Field", "Points at", "Answered by"], rows);
    }

    // Every cross-reference a stood-up type declares at another stood-up type, in a fixed order: by the
    // type a reader looks up, then by the field they write.
    private static IEnumerable<(TypeSchema From, string Field, FieldSpec Spec, List<TypeSchema> To)> Edges(
        IEnumerable<TypeSchema> types, Dictionary<string, TypeSchema> adopted)
    {
        foreach (var t in types.OrderBy(t => t.DisplayName, StringComparer.Ordinal))
        foreach (var name in t.FieldOrder.OrderBy(n => n, StringComparer.Ordinal))
        {
            if (!t.Fields.TryGetValue(name, out var field) || field.Refs.Count == 0) continue;

            var targets = field.Refs.Where(adopted.ContainsKey).Select(r => adopted[r]).ToList();
            if (targets.Count > 0) yield return (t, name, field, targets);
        }
    }

    // The same edges as a diagram, which answers a different question from the table: what shape the graph
    // is, rather than which field to write. A reciprocal pair is one edge here and two rows there, and both
    // are right: the graph has one relationship where an author has two fields to fill in.
    //
    // Written to the subset of Mermaid an Azure DevOps wiki renders, which is narrower than Mermaid's own
    // and fails silently where a diagram exceeds it. Use `graph`, never `flowchart`, and `-->`, never a
    // longer arrow. No subgraphs, because ADO does not support a link crossing one. GitHub renders this
    // subset too, so the fence goes in rather than ADO's `:::` container, which it shows as literal text.
    //
    // Edges carry their label as `-- text -->` rather than `-->|text|`. A markdown formatter reading the
    // file for tables finds the pipes in the second form and reformats the fenced block as cells.
    public static string RelationDiagram(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);
        var diagram = new StringBuilder("```mermaid\ngraph LR;\n");

        foreach (var t in adopted.Values.OrderBy(t => t.DisplayName, StringComparer.Ordinal))
            diagram.Append($"  {Node(t.Key)}[{t.DisplayName}];\n");

        // Reciprocal halves collapse into the one edge they describe. Whichever half comes first names it.
        var drawn = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (from, name, field, targets) in Edges(types, adopted))
        foreach (var to in targets)
        {
            var pair = string.CompareOrdinal(from.Key, to.Key) < 0
                ? $"{from.Key}|{to.Key}"
                : $"{to.Key}|{from.Key}";
            if (field.Reciprocal is not null && !drawn.Add(pair)) continue;

            diagram.Append($"  {Node(from.Key)} -- {name} --> {Node(to.Key)};\n");
        }

        return diagram.Append("```").ToString();
    }

    // A mermaid node id. Prefixed and reduced to word characters, so a type whose folder carries a
    // hyphen, or is spelled `end`, cannot collide with the diagram's own grammar.
    private static string Node(string key) =>
        "t_" + new string([.. key.Select(c => char.IsLetterOrDigit(c) ? c : '_')]);

    // The calls that are genuinely close. A pair needs both of its types to say anything at all, so one
    // adopted and one not leaves the pair out. A corpus with no controls gains nothing from a paragraph on
    // how a standard differs from one.
    //
    // Sorted by heading, because that is the line a reader scans. Each pair is rendered from the side of
    // the type that declares it, so the heading names that type first and the reader meets the two in the
    // order the sentence beneath them uses.
    public static string Disambiguations(IEnumerable<TypeSchema> types)
    {
        var adopted = types.ToDictionary(t => t.Key, StringComparer.Ordinal);

        var entries = new List<(string Heading, string Text)>();
        foreach (var t in types)
        foreach (var (other, text) in t.Versus)
            if (adopted.TryGetValue(other, out var against))
                entries.Add(($"{t.DisplayName} vs {against.DisplayName}", text));

        return string.Join("\n\n", entries
            .OrderBy(e => e.Heading, StringComparer.Ordinal)
            .Select(e => Wrap($"**{e.Heading}.** {e.Text}")));
    }

    // Prose at the corpus's own margin. Generated tables are exempt, because a cell cannot be broken;
    // a paragraph can. One long line in a file everything else wraps reads as the generator exempting
    // itself from the rule it is regenerating the file to enforce.
    private const int Margin = 120;

    private static string Wrap(string text)
    {
        var line = new StringBuilder();
        var wrapped = new StringBuilder();

        foreach (var word in Unbreakable(text))
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > Margin)
            {
                wrapped.Append(line).Append('\n');
                line.Clear();
            }

            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }

        return wrapped.Append(line).ToString();
    }

    // The units a line may be broken between. Words, except that a markdown link is one unit however many
    // spaces its label holds: `[RFC 2119](…)` broken after `RFC` still renders, but it reads badly in the
    // source and a formatter meeting it puts it back. The generator would then write it out again on the
    // next run. A word longer than the margin is left whole, a URL being the usual case.
    private static IEnumerable<string> Unbreakable(string text)
    {
        var words = text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        var link = new StringBuilder();

        foreach (var word in words)
        {
            if (link.Length == 0 && !word.StartsWith('[') && !word.StartsWith("**[", StringComparison.Ordinal))
            {
                yield return word;
                continue;
            }

            if (link.Length > 0) link.Append(' ');
            link.Append(word);

            // Closed once the target that follows the label has closed too. A bracket in prose that never
            // reaches one is released at the end, rather than swallowing the rest of the paragraph.
            if (word.Contains(')', StringComparison.Ordinal))
            {
                yield return link.ToString();
                link.Clear();
            }
        }

        if (link.Length > 0) yield return link.ToString();
    }

    // The corpus's own index of types, for whoever arrives at the corpus root: what each holds, and one
    // way on to the taxonomy, which answers "so where does mine go". The pointer sits inside the block so
    // it cannot drift above the table or be edited away.
    //
    // Sorted by name, because a reader looking a type up already knows its name. Tier is a column rather
    // than a grouping for the same reason: worth seeing beside a type, and not how anyone arrives.
    public static string TypesIndex(IEnumerable<TypeSchema> types, string taxonomyPath, string up) =>
        Gfm.RenderTable(["Type", "Tier", "What it holds"],
        [
            .. types.OrderBy(t => t.DisplayName, StringComparer.Ordinal).Select(t => new List<string>
                { $"[{t.DisplayName}]({Link(t, up)})", t.Tier, Gfm.Escape(t.Summary) })
        ])
        + "\n\n" + Wrap($"**Where does a document go?** The [taxonomy]({taxonomyPath}) has the decision table, "
                        + "what each type is and is not, and the calls that are genuinely close.");

    // The rows of an index, in the order the type's `index` block asks for. Sorting on several columns is
    // a sort by the first, ties broken by the next. The direction applies to the whole ordering, because a
    // type that wanted one column each way would be asking two questions in one key.
    //
    // A type declaring no `sort:` is sorted by id, which is the one column every document carries.
    private static IEnumerable<Doc> Sorted(TypeSchema t, List<Doc> docs)
    {
        var keys = t.IndexSort.Count > 0 ? t.IndexSort : ["id"];
        var descending = t.IndexOrder == Descending;

        var ordered = descending
            ? docs.OrderByDescending(d => d.FrontScalar(keys[0]) ?? "", StringComparer.Ordinal)
            : docs.OrderBy(d => d.FrontScalar(keys[0]) ?? "", StringComparer.Ordinal);

        return keys.Skip(1).Aggregate(ordered, (acc, key) => descending
            ? acc.ThenByDescending(d => d.FrontScalar(key) ?? "", StringComparer.Ordinal)
            : acc.ThenBy(d => d.FrontScalar(key) ?? "", StringComparer.Ordinal));
    }

    // One cell of an index row. A column names a frontmatter field, and how its value reads across a
    // table is the field's shape rather than the column's: a scalar is itself, a list of scalars is its
    // entries, and a list of objects is what names each entry.
    //
    // That last reading is what an index is for. `aligns-with` groups a framework with the clauses of it
    // a policy maps to, and an index carrying every clause of every framework would be a column wider
    // than the rest of the table put together. The framework names answer what a reader scans an index
    // to ask, which is who a policy touches, and the record answers where.
    private static string Cell(Doc d, string col, TypeSchema t)
    {
        if (col == Title)
        {
            // The index sits in the type's own folder, so a record filed under a category below it is
            // reached through that category. `Folder` is the first segment of `Rel`, so what remains
            // after it is the link, and a record sitting flat is left with its filename.
            var file = d.Folder.Length > 0 && d.Rel.Length > d.Folder.Length
                ? d.Rel[(d.Folder.Length + 1)..]
                : Path.GetFileName(d.Rel);
            return $"[{Gfm.Escape(d.H1 ?? "")}]({file})";
        }

        if (d.FrontScalar(col) is { Length: > 0 } scalar) return Gfm.Escape(scalar);

        var spec = t.Fields.GetValueOrDefault(col);
        var naming = spec?.Of == "object" && spec.Entry is [{ } first, ..] ? first.Name : null;
        return Gfm.Escape(string.Join(", ", d.FrontEntries(col, naming)));
    }

    // The frontmatter reference on a type page: every field a document of that type carries, universal
    // ones included, so the page an author writes from is complete without sending them to metadata.md
    // for id, tier and owner.
    //
    // Universal fields come first, in the universal order, and are read through EffectiveField. A type
    // that refines one shows the refinement rather than the universal placeholder, and every type narrows
    // `status` to its own values. The universal ones are marked rather than separated: one table is one
    // scan, which is what someone filling in frontmatter wants.
    public static string SchemaTable(TypeSchema t, Schema s, string up)
    {
        List<string> headers = ["Field", "Value", "Notes"];
        var universal = s.UniversalOrder.Where(n => s.EffectiveField(t, n) is not null).ToList();
        var own = t.FieldOrder.Where(n => !universal.Contains(n)).ToList();

        var rows = universal.Select(n => FieldRow(n, s.DeclaredField(t, n), true))
            .Concat(own.Select(n => FieldRow(n, t.Fields[n], false)))
            .ToList();

        var order = universal.Concat(own).ToList();
        var specs = order.Select(n => s.DeclaredField(t, n)).ToList();
        var table = Gfm.RenderTable(headers, rows);
        return table + Legend(specs.Any(f => f.Required), universal.Count > 0, up);

        // `tier` is the one field whose value a type settles rather than chooses from: every document in
        // the folder carries the same one, and CI fails any that does not. Offering the reader the other
        // four would be offering four ways to fail a check.
        List<string> FieldRow(string name, FieldSpec f, bool universal) =>
        [
            $"`{name}`{Marks(f.Required, universal)}",
            name == "tier" && t.Tier.Length > 0 ? $"`{t.Tier}`" : ValueFor(f),
            NotesFor(f)
        ];
    }

    // What a field may hold: its type, or the values themselves where the type is an enum with a resolved
    // set. The word `enum` tells an author nothing they can write into frontmatter. The set is what they
    // came to the page for, so the set is what the column carries.
    //
    // A derived field carries neither. Nothing an author types lands in it, so the column that would
    // tell them what to write says where the value comes from instead.
    private static string ValueFor(FieldSpec f) =>
        f.From is { } from
            ? $"derived from the record's {from}"
            : f.Type is "enum" && f.Values is { Count: > 0 } values
                ? string.Join(" ", values.Select(v => $"`{v}`"))
                : f.Type;

    // The same reference for metadata.md, which documents the universal fields once for the whole
    // taxonomy. Values are the unrefined universal declarations: with no type in hand to narrow it,
    // `status` genuinely varies by type here.
    public static string UniversalSchemaTable(Schema s)
    {
        List<string> headers = ["Field", "Value", "Notes"];
        var fields = s.UniversalOrder.Where(s.Universal.ContainsKey).Select(n => s.Universal[n]).ToList();
        var rows = fields
            .Select(f => new List<string>
                { $"`{f.Name}`{Marks(f.Required, false)}", ValueFor(f), NotesFor(f) })
            .ToList();
        return Gfm.RenderTable(headers, rows) + Legend(fields.Any(f => f.Required), false, "");
    }

    // Required and universal are marked on the field name rather than given a column of their own: a
    // column that is empty in most rows costs a full column's width to say one bit. The markers read in
    // the order the legend below the table explains them.
    private static string Marks(bool required, bool universal)
    {
        var marks = (required ? "*" : "") + (universal ? "†" : "");
        return marks.Length == 0 ? "" : $" {marks}";
    }

    // One paragraph beneath the table, a line to each marker. A hard break joins the two, which is two
    // trailing spaces. A blank line would make them two paragraphs where they are one legend, and spaces
    // on one line would collapse to a single gap, HTML reducing any run of them to one. The asterisk is
    // escaped: a line opening with a bare one is a bullet.
    private static string Legend(bool anyRequired, bool anyUniversal, string up)
    {
        List<string> parts = [];
        if (anyRequired) parts.Add("\\* Field is required");
        if (anyUniversal)
            parts.Add("† Carried by every document in the taxonomy. See "
                      + $"[Metadata]({up}knowledge-as-code/metadata.md).");
        return parts.Count == 0 ? "" : "\n\n" + string.Join("  \n", parts);
    }

    // Enum values are not repeated here. They are the Value column, which ValueFor renders. A required-when
    // condition closes the cell as its own sentence, quoted exactly as the schema writes it, because it is
    // the difference between a field an author may skip and one they may not.
    private static string NotesFor(FieldSpec f)
    {
        var notes = Gfm.Escape(f.TableText ?? "");
        if (string.IsNullOrEmpty(f.RequiredWhen)) return notes;

        var when = $"Required when `{Gfm.Escape(f.RequiredWhen)}`.";
        return notes.Length == 0 ? when : $"{notes} {when}";
    }

    private static string Humanize(string col)
    {
        if (col == "id") return "ID";
        var s = col.Replace('-', ' ');
        return char.ToUpperInvariant(s[0]) + s[1..];
    }
}
