using System.Text;

// ---------------------------------------------------------------------------
// Generation — index pages and the generated blocks in <type>.md
// ---------------------------------------------------------------------------

namespace kac.core;

public static class Generator
{
    private const string Banner =
        "<!-- Generated by `dotnet run .tooling/kac.cs -- index` — do not edit by hand; run that command to regenerate. -->";

    public static string IndexPage(TypeSchema t, List<Doc> docs)
    {
        // "Policy Index (POL)" — the type as a reader names it, then the id prefix they will meet in
        // every cross-reference. The prefix is dropped where it only repeats the name, so an ADR index
        // is headed "ADR Index" rather than "ADR Index (ADR)".
        var prefix = t.IdPrefix.ToUpperInvariant();
        var title = $"{t.DisplayName} Index"
                    + (prefix.Length > 0 && !string.Equals(prefix, t.DisplayName, StringComparison.OrdinalIgnoreCase)
                        ? $" ({prefix})"
                        : "");

        // An empty type still gets its index: every type page links to one, and link-resolves does not
        // check type root pages, so a withheld file would be an unchecked dead link. A headed table with
        // no rows says less than nothing, so an empty index says it is empty and points at the template.
        var body = docs.Count == 0
            ? $"_Nothing here yet — copy [`{Artefact.Template}`]({Artefact.Template}) to add the first._"
            : RenderTable(
                t.IndexColumns.Select(Humanize).ToList(),
                docs.OrderBy(d => d.FrontScalar(string.IsNullOrEmpty(t.IndexSort) ? "id" : t.IndexSort) ?? "",
                        StringComparer.Ordinal)
                    .Select(d => t.IndexColumns.Select(c => Cell(d, c)).ToList())
                    .ToList());

        return $"{Banner}\n\n# {title}\n\n{body}\n";
    }

    private static string Cell(Doc d, string col)
    {
        if (col == "title")
        {
            var file = Path.GetFileName(d.Rel);
            return $"[{Escape(d.H1 ?? "")}]({file})";
        }

        return Escape(d.FrontScalar(col) ?? "");
    }

    // The frontmatter reference on a type page: every field a document of that type carries, universal
    // ones included, so the page an author writes from is complete without sending them to metadata.md
    // for id, tier and owner.
    //
    // Universal fields come first, in the universal order, and are read through EffectiveField so a type
    // that refines one (every type narrows `status` to its own values) shows the refinement rather than
    // the universal placeholder. They are marked rather than separated: one table is one scan, which is
    // what someone filling in frontmatter wants.
    public static string SchemaTable(TypeSchema t, Schema s)
    {
        List<string> headers = ["Field", "Req", "Type", "Notes"];
        var universal = s.UniversalOrder.Where(n => s.EffectiveField(t, n) is not null).ToList();
        var own = t.FieldOrder.Where(n => !universal.Contains(n));

        var rows = universal.Select(n => Row(n, s.EffectiveField(t, n)!, true))
            .Concat(own.Select(n => Row(n, t.Fields[n], false)))
            .ToList();

        var order = universal.Concat(own).ToList();
        var specs = order.Select(n => s.EffectiveField(t, n)!).ToList();
        var table = RenderTable(headers, rows) + EnumValues(specs) + ConditionalFields(specs);
        return universal.Count == 0
            ? table
            : $"{table}\n\n† Carried by every document in the taxonomy — see "
              + "[Metadata](/knowledge-as-code/metadata.md).";

        static List<string> Row(string name, FieldSpec f, bool universal) =>
            [$"`{name}`{(universal ? " †" : "")}", f.Required ? "●" : "", f.Type, NotesFor(f)];
    }

    // Enum values are data, not prose, and they belong in a table of their own rather than in a Notes
    // cell. The renderer pads every column to its widest cell, so one multi-value enum in Notes widens
    // every row of the table — and these pages are read as source as much as rendered, which makes
    // width the constraint that matters.
    private static string EnumValues(IEnumerable<FieldSpec> fields)
    {
        var enums = fields.Where(f => f is { Type: "enum", Values.Count: > 0 }).ToList();
        if (enums.Count == 0) return "";

        List<string> headers = ["Field", "Values"];
        var rows = enums
            .Select(f => new List<string>
                { $"`{f.Name}`", string.Join(" · ", f.Values!.Select(v => $"`{v}`")) })
            .ToList();
        return "\n\n**Enum values**\n\n" + RenderTable(headers, rows);
    }

    // Same reasoning as EnumValues, and a required-when condition has to be quoted exactly, so it is the
    // last thing that should be competing for room in a Notes cell.
    private static string ConditionalFields(IEnumerable<FieldSpec> fields)
    {
        var conditional = fields.Where(f => !string.IsNullOrEmpty(f.RequiredWhen)).ToList();
        if (conditional.Count == 0) return "";

        List<string> headers = ["Field", "Required when"];
        var rows = conditional
            .Select(f => new List<string> { $"`{f.Name}`", $"`{f.RequiredWhen}`" })
            .ToList();
        return "\n\n**Conditionally required**\n\n" + RenderTable(headers, rows);
    }

    // The same reference for metadata.md, which documents the universal fields once for the whole
    // taxonomy. Values are the unrefined universal declarations — `status` is genuinely "varies by
    // type" here, because there is no type in hand to narrow it.
    public static string UniversalSchemaTable(Schema s)
    {
        List<string> headers = ["Field", "Req", "Type", "Notes"];
        var fields = s.UniversalOrder.Where(s.Universal.ContainsKey).Select(n => s.Universal[n]).ToList();
        var rows = fields
            .Select(f => new List<string> { $"`{f.Name}`", f.Required ? "●" : "", f.Type, NotesFor(f) })
            .ToList();
        return RenderTable(headers, rows) + EnumValues(fields) + ConditionalFields(fields);
    }

    private static string NotesFor(FieldSpec f)
    {
        // Enum values and required-when conditions are not repeated here — both render in their own
        // tables beneath, see EnumValues and ConditionalFields.
        return Escape(f.TableText ?? "");
    }

    // The reader-facing "What CI checks" table: a curated, grouped view of the catalogue that `kac index`
    // splices into every type page. It is deliberately NOT the raw catalogue — related checks are folded
    // into one row (the three `id-*` checks read as one `id` row) and worded for a human skim. Generating
    // it from the catalogue instead would change what the table means, so each row names the catalogue
    // ids it stands for and ChecksTableProblems verifies the coverage, leaving the wording hand-tuned.
    //
    // `When` is the row's applicability: null fires for every type, otherwise the predicate asks the
    // type's own schema whether the check can fire at all — so a policy page does not advertise that its
    // documents are checked for Y-statements. Read from the schema rather than hand-listed per type, so
    // declaring a rule remains the only thing needed to document it.
    private static readonly (string Label, string[] Ids, string Description, Func<TypeSchema, bool>? When)[] DocRows =
    [
        ("frontmatter-parses", ["frontmatter-parses"], "Frontmatter is present and is a valid YAML mapping.", null),
        ("unknown-key", ["unknown-key"], "Every frontmatter key is a schema field or a reserved ADO key.", null),
        ("key-order", ["key-order"], "Key order is a topological extension of the schema's field order.", null),
        ("required-field", ["required-field"], "Required and conditionally-required fields are present.", null),
        ("bare-key", ["bare-key"], "An absent value is a bare key, never `null`, `~`, `\"\"` or `—`.", null),
        ("date-quoted / date-format", ["date-quoted", "date-format"], "Date fields are quoted `YYYY-MM-DD`.", null),
        ("enum", ["enum", "enum-lowercase"], "Enum values are in range and lowercase.", null),
        ("field-pattern", ["field-pattern"],
            "Values match the pattern their field declares (e.g. `tags`).", null),
        ("list-order", ["list-order"],
            "List entries read in alphabetical order, with numbers compared as numbers.", null),
        ("tier-matches-type", ["tier-matches-type"], "`tier` matches the tier the type declares.", null),
        ("id", ["id-prefix", "id-format", "id-matches-filename"],
            "`id` carries the type's prefix and matches the filename's number or mnemonic.", null),
        ("id-unique", ["id-unique"], "`id` is unique across the whole wiki.", null),
        ("filename / slug-length", ["filename-pattern", "slug-length"],
            "Filename matches the pattern; the slug is within 30 characters.", null),
        ("h1", ["h1"], "The document has an H1.", null),
        ("identity", ["identity", "identity-type", "identity-id", "identity-status"],
            "An identity line beneath the H1 names the type, id and status, and all three agree with the frontmatter.",
            t => !t.IsSingleDocument),
        ("required-section", ["required-section"], "Every required section heading is present.", null),
        // The pipe is escaped because this text lands in a table cell: GFM splits a cell on a bare `|`
        // even inside a code span, so an unescaped one would break the row it is describing.
        ("clauses", ["clause-table", "clause-id-format", "clause-id-unique", "clause-modal"],
            "The clause section is a table of `Id \\| Clause` rows, each id a unique code span and each "
            + "clause opening with its modal.", t => t.Clauses is not null),
        ("clause-order / clause-compound", ["clause-order", "clause-compound"],
            "Clause rows are grouped by binding level, and each carries a single obligation.",
            t => t.Clauses is not null),
        // Shown on the pages inside the clause machinery — the types that declare clauses — rather than
        // on every page. The check itself runs corpus-wide, since a citation is checked where it is
        // written and any document may carry one; what this predicate scopes is the documentation, and
        // a type with no clauses in sight has no reason to describe how they are cited.
        ("clause-ref", ["clause-ref"],
            "A `pol-XXXX.CLAUSE` citation names a clause that exists.", t => t.Clauses is not null),
        ("link-resolves", ["link-resolves"], "Every internal link resolves (all link forms, `.md` optional).", null),
        ("undefined-label", ["undefined-label"], "Every shortcut reference has a link definition.", null),
        ("label-canonical", ["label-canonical"],
            "A shortcut label that names a document is written as that document's id.", null),
        ("related-matches-section", ["related-matches-section"],
            "A field that mirrors a section reconciles with the ids in that section.",
            t => t.AnyField(f => f.MirrorsSection is not null)),
        ("reciprocal", ["reciprocal"], "A reciprocal field and its counterpart agree in both directions.",
            t => t.AnyField(f => f.Reciprocal is not null)),
        ("unused-definition", ["unused-definition"], "A link definition that nothing references.", null),
        ("y-statement", ["y-statement"],
            "A Y-statement block-quote follows the H1, states all six moves, and is within 60 words.",
            t => t.HasRule("y-statement-present")),
        ("alternatives-verdict", ["alternatives-verdict"], "Each Alternatives Considered bullet states a verdict.",
            t => t.HasRule("alternatives-have-verdicts"))
    ];

    // Catalogue checks the reader-facing table deliberately does not surface: `type` (an internal
    // folder→schema guard a well-formed document never trips), `list` (a low-level YAML-shape check
    // subsumed by the field descriptions) and `bracket-literal` (a heuristic sibling of
    // undefined-label). Every OTHER catalogue id must appear in DocRows — ChecksTableProblems fails
    // otherwise, so a new check cannot silently go undocumented.
    // `type-setup` joins them for a different reason: it checks whether the type is stood up at all,
    // and this table is rendered onto the very page whose absence it reports. A reader who can see the
    // row does not need it.
    // `generated-block` joins them alongside `type-setup`, for the same reason: both are checks on
    // the type page itself rather than on a document of that type, and this table describes what a
    // contributor's document is held to.
    // The three `schema-*` checks join them for the furthest-out version of that reason: they read the
    // schema rather than any document, and what they report is a defect in the file this very table is
    // generated from. Their audience is whoever edits `.schema/`, and `.schema/README.md` is where they
    // are documented.
    private static readonly HashSet<string> IntentionallyUndocumented =
        new(["type", "list", "bracket-literal", "type-setup", "generated-block",
            "schema-unreadable", "schema-dispatch", "schema-shape"], StringComparer.Ordinal);

    // The curated rows, then a row for each expression rule the type declares. A core check is worded
    // here because several ids fold into one reader-facing row; an expression rule is one id reporting
    // under its own name, and its `description:` in the schema is already that row written out. Copying
    // it here would be the same sentence in two files, drifting apart at the first edit.
    //
    // Beneath both, the rules the type declares and nothing runs. See Intentions.
    public static string ChecksTable(TypeSchema t)
    {
        var severity = CheckCatalogue.All.ToDictionary(c => c.Id, c => c.Severity);
        List<string> headers = ["Check", "Level", "What it verifies"];
        var rows = DocRows.Where(r => r.When is null || r.When(t)).Select(r => new List<string>
        {
            $"`{r.Label}`",
            severity.GetValueOrDefault(r.Ids[0], Sev.Error).ToString().ToLowerInvariant(),
            r.Description
        }).ToList();

        rows.AddRange(t.Rules.Where(r => r.Compiled is not null).Select(r => new List<string>
        {
            $"`{r.Id}`",
            (r.Severity ?? Sev.Warning).ToString().ToLowerInvariant(),
            Escape(r.Description ?? r.Message ?? "")
        }));

        return RenderTable(headers, rows) + Intentions(t);
    }

    // The rules the type declares that nothing runs — no `expr:`, no implementation. Each is a real
    // decision about what this type should be held to, and each is unenforced, so a page that showed
    // only the table above would say the schema promises nothing more than CI delivers. It promises
    // rather a lot more, and that is worth a reader knowing before they rely on it.
    //
    // Kept apart from the table rather than folded in as rows, because the two answer different
    // questions: one is what a build will say about a document, the other what has been written down
    // and not built. A rule leaves this block by gaining an `expr:` or a class, at which point it
    // appears above under its own name.
    private static string Intentions(TypeSchema t)
    {
        var intended = t.Rules
            .Where(r => r.Compiled is null && !DocumentRules.ByRuleId.ContainsKey(r.Id))
            .ToList();
        if (intended.Count == 0) return "";

        List<string> headers = ["Rule", "What it would verify"];
        var rows = intended
            .Select(r => new List<string> { $"`{r.Id}`", Escape(r.Description ?? r.Message ?? "") })
            .ToList();
        return "\n\n**Declared, not yet enforced** — carried by the schema, run by nothing.\n\n"
               + RenderTable(headers, rows);
    }

    // Reconcile the curated table with the catalogue. Empty means the reader-facing table is a
    // faithful, complete view of what the validator enforces; any entry is a drift a human must
    // resolve. `kac checks` calls this and fails on a non-empty result, which the test suite asserts.
    public static IReadOnlyList<string> ChecksTableProblems()
    {
        var catalogue = CheckCatalogue.All.Select(c => c.Id).ToHashSet(StringComparer.Ordinal);
        var documented = DocRows.SelectMany(r => r.Ids).ToHashSet(StringComparer.Ordinal);
        var problems = new List<string>();

        foreach (var id in documented.Where(id => !catalogue.Contains(id)).Order(StringComparer.Ordinal))
            problems.Add($"the checks table documents '{id}', which is not a catalogue check (stale row).");
        foreach (var id in catalogue.Where(id => !documented.Contains(id) && !IntentionallyUndocumented.Contains(id))
                     .Order(StringComparer.Ordinal))
            problems.Add(
                $"catalogue check '{id}' is neither in the checks table nor waived in IntentionallyUndocumented.");
        foreach (var id in IntentionallyUndocumented.Where(id => documented.Contains(id) || !catalogue.Contains(id))
                     .Order(StringComparer.Ordinal))
            problems.Add(
                $"'{id}' is waived in IntentionallyUndocumented but is documented or unknown — drop the waiver.");

        return problems;
    }

    public static string SpliceBlock(string text, string name, string inner)
    {
        var begin = $"<!-- BEGIN GENERATED: {name} -->";
        var end = $"<!-- END GENERATED: {name} -->";
        var bi = text.IndexOf(begin, StringComparison.Ordinal);
        if (bi < 0) return text;
        var ei = text.IndexOf(end, bi, StringComparison.Ordinal);
        if (ei < 0) return text;
        return text[..(bi + begin.Length)] + "\n\n" + inner + "\n\n" + text[ei..];
    }

    // Deterministic GFM table: fixed column widths, single-space padding, LF joins,
    // no trailing newline (callers add their own).
    private static string RenderTable(List<string> headers, List<List<string>> rows)
    {
        var n = headers.Count;
        var w = new int[n];
        for (var i = 0; i < n; i++) w[i] = headers[i].Length;
        foreach (var row in rows)
            for (var i = 0; i < n; i++)
                w[i] = Math.Max(w[i], row[i].Length);

        List<string> lines =
        [
            Row(headers, w), Sep(w),
            .. rows.Select(r => Row(r, w))
        ];
        return string.Join("\n", lines);
    }

    private static string Row(List<string> cells, int[] w)
    {
        var sb = new StringBuilder("|");
        for (var i = 0; i < cells.Count; i++)
            sb.Append(' ').Append(cells[i].PadRight(w[i])).Append(" |");
        return sb.ToString();
    }

    // Dashes fill the cell, padding spaces included: |------| rather than | ---- |. Both are valid
    // GFM and the row width is identical, but this is the form markdown formatters normalise to, and
    // a generated file that an editor reformats on save is a permanently dirty working tree.
    private static string Sep(int[] w)
    {
        var sb = new StringBuilder("|");
        foreach (var width in w)
            sb.Append(new string('-', Math.Max(3, width + 2))).Append('|');
        return sb.ToString();
    }

    private static string Humanize(string col)
    {
        if (col == "id") return "ID";
        var s = col.Replace('-', ' ');
        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    private static string Escape(string cell)
        => cell.Replace("\r", " ").Replace("\n", " ").Replace("|", "\\|");
}
