using System.Text;

// ---------------------------------------------------------------------------
// Generation — INDEX pages and the generated blocks in <type>.md
// ---------------------------------------------------------------------------

namespace kac.core;

public static class Generator
{
    private const string Banner =
        "<!-- Generated by `dotnet run .tooling/kac.cs -- index` — do not edit by hand; run that command to regenerate. -->";

    public static string IndexPage(TypeSchema t, List<Doc> docs)
    {
        var headers = t.IndexColumns.Select(Humanize).ToList();
        var sort = string.IsNullOrEmpty(t.IndexSort) ? "id" : t.IndexSort;
        var rows = docs
            .OrderBy(d => d.FrontScalar(sort) ?? "", StringComparer.Ordinal)
            .Select(d => t.IndexColumns.Select(c => Cell(d, c)).ToList())
            .ToList();

        var title = t.IdPrefix.ToUpperInvariant() + " Index";
        return $"{Banner}\n\n# {title}\n\n{RenderTable(headers, rows)}\n";
    }

    private static string Cell(Doc d, string col)
    {
        if (col == "title")
        {
            var file = Path.GetFileName(d.Rel);
            return $"[{Escape(d.TitleText())}]({file})";
        }

        return Escape(d.FrontScalar(col) ?? "");
    }

    // The frontmatter reference on a type page: every field a document of that type carries, universal
    // ones included. Showing only the type's own declarations left three required fields (id, tier,
    // owner) off the page an author writes from, on the argument that metadata.md covers them — but a
    // reader following that argument has to leave the page, and metadata.md drifted anyway.
    //
    // Universal fields come first, in the universal order, and are read through EffectiveField so a
    // type that refines one (every type narrows `status` to its own values) shows the refinement rather
    // than the universal placeholder. They are marked rather than separated: one table is one scan,
    // which is what someone filling in frontmatter actually wants.
    public static string SchemaTable(TypeSchema t, Schema s)
    {
        List<string> headers = ["Field", "Req", "Type", "Notes"];
        var universal = s.UniversalOrder.Where(n => s.EffectiveField(t, n) is not null).ToList();
        var own = t.FieldOrder.Where(n => !universal.Contains(n));

        var rows = universal.Select(n => Row(n, s.EffectiveField(t, n)!, true))
            .Concat(own.Select(n => Row(n, t.Fields[n], false)))
            .ToList();

        var order = universal.Concat(own).ToList();
        var table = RenderTable(headers, rows) + EnumValues(order.Select(n => s.EffectiveField(t, n)!));
        return universal.Count == 0
            ? table
            : $"{table}\n\n† Carried by every document in the taxonomy — see "
              + "[Metadata](/knowledge-as-code/metadata.md).";

        static List<string> Row(string name, FieldSpec f, bool universal) =>
            [$"`{name}`{(universal ? " †" : "")}", f.Required ? "●" : "", f.Type, NotesFor(f)];
    }

    // Enum values are data, not prose, and inside a Notes cell they were the single thing blowing the
    // table out: `tier`'s five values plus its description came to 153 characters, and because the
    // renderer pads every column to its widest cell that one field made every row 190 wide. These
    // pages are read as code as much as rendered, so width is the constraint that matters — a table
    // of its own keeps the values to ~84 characters and stops a six-value enum widening every row.
    private static string EnumValues(IEnumerable<FieldSpec> fields)
    {
        var enums = fields.Where(f => f is { Type: "enum", Values.Count: > 0 }).ToList();
        if (enums.Count == 0) return "";

        List<string> headers = ["Field", "Values"];
        var rows = enums
            .Select(f => new List<string>
                { $"`{f.Name}`", string.Join(" · ", f.Values!.Select(v => $"`{v}`")) })
            .ToList();
        return "\n\n**Enum values**\n\n" + RenderTable(headers, rows);
    }

    // The same reference for metadata.md, which documents the universal fields once for the whole
    // taxonomy. Values are the unrefined universal declarations — `status` is genuinely "varies by
    // type" here, because there is no type in hand to narrow it.
    public static string UniversalSchemaTable(Schema s)
    {
        List<string> headers = ["Field", "Req", "Type", "Notes"];
        var fields = s.UniversalOrder.Where(s.Universal.ContainsKey).Select(n => s.Universal[n]).ToList();
        var rows = fields
            .Select(f => new List<string> { $"`{f.Name}`", f.Required ? "●" : "", f.Type, NotesFor(f) })
            .ToList();
        return RenderTable(headers, rows) + EnumValues(fields);
    }

    private static string NotesFor(FieldSpec f)
    {
        // Enum values are not repeated here — they render beneath the table, see EnumValues.
        var parts = new List<string>();
        if (!string.IsNullOrEmpty(f.TableText)) parts.Add(f.TableText);
        if (!string.IsNullOrEmpty(f.RequiredWhen))
            parts.Add($"Required once `{f.RequiredWhen.Split("==").Last().Trim()}`.");
        return Escape(string.Join(" ", parts));
    }

    // The reader-facing "What CI checks" table: a curated, grouped view of the catalogue that
    // `kac index` splices into every type page. It is deliberately NOT the raw catalogue — related
    // checks are folded into one row (e.g. the three `id-*` checks read as one `id` row) and worded
    // for a human skim. Each row therefore names the catalogue ids it stands for, so the table's
    // coverage stays verifiable (ChecksTableProblems) even though its presentation is hand-tuned.
    //
    // `When` is the row's applicability: null means the check fires for every type, otherwise the
    // predicate asks the type's own schema whether it can fire at all. Without it the table was a
    // single ADR-shaped list spliced into every page, telling a policy reader that their documents
    // are checked for Y-statements. Applicability is read from the schema rather than hand-listed
    // per type, so declaring a rule is still the only thing needed to document it.
    private static readonly (string Label, string[] Ids, string Description, Func<TypeSchema, bool>? When)[] DocRows =
    [
        ("frontmatter-parses", ["frontmatter-parses"], "Frontmatter is present and is a valid YAML mapping.", null),
        ("unknown-key", ["unknown-key"], "Every frontmatter key is a schema field or a reserved ADO key.", null),
        ("key-order", ["key-order"], "Key order is a topological extension of the schema's field order.", null),
        ("required-field", ["required-field"], "Required and conditionally-required fields are present.", null),
        ("bare-key", ["bare-key"], "An absent value is a bare key, never `null`, `~`, `\"\"` or `—`.", null),
        ("date-quoted / date-format", ["date-quoted", "date-format"], "Date fields are quoted `YYYY-MM-DD`.", null),
        ("enum", ["enum", "enum-lowercase"], "Enum values are in range and lowercase.", null),
        ("field-pattern", ["field-pattern"],
            "Values match the pattern their field declares (e.g. `tags`).", null),
        ("tier-matches-type", ["tier-matches-type"], "`tier` matches the tier the type declares.", null),
        ("id", ["id-prefix", "id-format", "id-matches-filename"],
            "`id` carries the type's prefix and, where the type is numbered, matches the filename number.", null),
        ("id-unique", ["id-unique"], "`id` is unique across the whole wiki.", null),
        ("filename / slug-length", ["filename-pattern", "slug-length"],
            "Filename matches the pattern; the slug is within 30 characters.", null),
        ("h1", ["h1", "h1-pattern", "h1-matches-id"],
            "The document has an H1 and, where the type declares one, it matches the title pattern.", null),
        ("required-section", ["required-section"], "Every required section heading is present.", null),
        ("link-resolves", ["link-resolves"], "Every internal link resolves (all link forms, `.md` optional).", null),
        ("undefined-label", ["undefined-label"], "Every shortcut reference has a link definition.", null),
        ("related-matches-section", ["related-matches-section"],
            "A field that mirrors a section reconciles with the ids in that section.",
            t => t.AnyField(f => f.MirrorsSection is not null)),
        ("reciprocal", ["reciprocal"], "A reciprocal field and its counterpart agree in both directions.",
            t => t.AnyField(f => f.Reciprocal is not null)),
        ("unused-definition", ["unused-definition"], "A link definition that nothing references.", null),
        ("y-statement", ["y-statement"], "A Y-statement block-quote follows the H1 and is within 60 words.",
            t => t.HasRule("y-statement-present")),
        ("alternatives-verdict", ["alternatives-verdict"], "Each Alternatives Considered bullet states a verdict.",
            t => t.HasRule("alternatives-have-verdicts"))
    ];

    // Catalogue checks the reader-facing table deliberately does not surface: `type` (an internal
    // folder→schema guard a well-formed document never trips), `list` (a low-level YAML-shape check
    // subsumed by the field descriptions) and `bracket-literal` (a heuristic sibling of
    // undefined-label). Every OTHER catalogue id must appear in DocRows — ChecksTableProblems fails
    // otherwise, so a new check cannot silently go undocumented.
    private static readonly HashSet<string> IntentionallyUndocumented =
        new(["type", "list", "bracket-literal"], StringComparer.Ordinal);

    public static string ChecksTable(TypeSchema t)
    {
        var severity = CheckCatalogue.All.ToDictionary(c => c.Id, c => c.Severity);
        List<string> headers = ["Check", "Level", "What it verifies"];
        var rows = DocRows.Where(r => r.When is null || r.When(t)).Select(r => new List<string>
        {
            $"`{r.Label}`",
            severity.GetValueOrDefault(r.Ids[0], Sev.Error).ToString().ToLowerInvariant(),
            r.Description
        }).ToList();
        return RenderTable(headers, rows);
    }

    // Reconcile the curated table with the catalogue. Empty means the reader-facing table is a
    // faithful, complete view of what the validator enforces; any entry is a drift a human must
    // resolve. `kac checks` calls this and fails on a non-empty result, which the test suite asserts.
    public static IReadOnlyList<string> ChecksTableProblems()
    {
        var catalogue = CheckCatalogue.All.Select(c => c.Id).ToHashSet(StringComparer.Ordinal);
        var documented = DocRows.SelectMany(r => r.Ids).ToHashSet(StringComparer.Ordinal);
        var problems = new List<string>();

        foreach (var id in documented.Where(id => !catalogue.Contains(id)).Order(StringComparer.Ordinal))
            problems.Add($"the checks table documents '{id}', which is not a catalogue check (stale row).");
        foreach (var id in catalogue.Where(id => !documented.Contains(id) && !IntentionallyUndocumented.Contains(id))
                     .Order(StringComparer.Ordinal))
            problems.Add(
                $"catalogue check '{id}' is neither in the checks table nor waived in IntentionallyUndocumented.");
        foreach (var id in IntentionallyUndocumented.Where(id => documented.Contains(id) || !catalogue.Contains(id))
                     .Order(StringComparer.Ordinal))
            problems.Add(
                $"'{id}' is waived in IntentionallyUndocumented but is documented or unknown — drop the waiver.");

        return problems;
    }

    public static string SpliceBlock(string text, string name, string inner)
    {
        var begin = $"<!-- BEGIN GENERATED: {name} -->";
        var end = $"<!-- END GENERATED: {name} -->";
        var bi = text.IndexOf(begin, StringComparison.Ordinal);
        if (bi < 0) return text;
        var ei = text.IndexOf(end, bi, StringComparison.Ordinal);
        if (ei < 0) return text;
        return text[..(bi + begin.Length)] + "\n\n" + inner + "\n\n" + text[ei..];
    }

    // Deterministic GFM table: fixed column widths, single-space padding, LF joins,
    // no trailing newline (callers add their own).
    private static string RenderTable(List<string> headers, List<List<string>> rows)
    {
        var n = headers.Count;
        var w = new int[n];
        for (var i = 0; i < n; i++) w[i] = headers[i].Length;
        foreach (var row in rows)
            for (var i = 0; i < n; i++)
                w[i] = Math.Max(w[i], row[i].Length);

        List<string> lines =
        [
            Row(headers, w), Sep(w),
            .. rows.Select(r => Row(r, w))
        ];
        return string.Join("\n", lines);
    }

    private static string Row(List<string> cells, int[] w)
    {
        var sb = new StringBuilder("|");
        for (var i = 0; i < cells.Count; i++)
            sb.Append(' ').Append(cells[i].PadRight(w[i])).Append(" |");
        return sb.ToString();
    }

    private static string Sep(int[] w)
    {
        var sb = new StringBuilder("|");
        foreach (var width in w)
            sb.Append(' ').Append(new string('-', Math.Max(3, width))).Append(" |");
        return sb.ToString();
    }

    private static string Humanize(string col)
    {
        if (col == "id") return "ID";
        var s = col.Replace('-', ' ');
        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    private static string Escape(string cell)
        => cell.Replace("\r", " ").Replace("\n", " ").Replace("|", "\\|");
}
